const blogs = [
  {
    'title': 'a healthy outlet',
    'date': 'January 24, 2020',
    'message': 'Writing has always been my guilty pleasure. It’s been my personal way of coping through life and a part of me selfishly wants to keep it private. But I realized I need to prohibit myself from believing the lie that struggles should be internalized. I want to stop marginalizing my process and leaving them as this “taboo” topic too awkward, too uncomfortable to be voiced. Accountability is an imperative part of growth. I can secretly write my feelings away, but if there’s no follow up- what’s the point? Ultimately, this is why I decided to publicly share this blog.\n I looked back at my old journals and had this instantaneous epiphany: my words stand as a pillar of my experiences. I’m learning that there’s growth in the midst of writing. There’s perceivable change behind every line. I wanted to start this blog a year ago. But damn, fear is a real thing. A solid year went by with 0 progress. A solid year of orienting my hand away from anything demanding vulnerability. A solid year of muting a process that fear had decided wasn’t worthy to be voiced. To be honest, I’m still afraid. Public blogs turn into palpable words which come with the consequence of a weight I’m not sure I’m ready to carry. However, it provides a backbone. Writing = introspection and being able to publicly share my thoughts = accountability.  If I don’t cease the moment and write… my journey will inevitably end up as an evanescent process.\nC.S Lewis wrote, “The typical expression of opening friendship would be something like, \‘What? You too? I thought I was the only one!\'” My heart is to capture my process, but more importantly, to empower others. Hopefully, this can turn into conversation starters and a push out of your own comfort zone! Vulnerability is hard but to love is to be vulnerable and that’s the kind of culture I hope to cultivate this year. So here’s to the start of authenticity and expressive passion that refuses to let fear shame its love for language.'
  },
  {
    'title': 'an unhealthy outlet',
    'date': 'January 26, 2020',
    'message': 'Writing has always been my guilty pleasure. It’s been my personal way of coping through life and a part of me selfishly wants to keep it private. But I realized I need to prohibit myself from believing the lie that struggles should be internalized. I want to stop marginalizing my process and leaving them as this “taboo” topic too awkward, too uncomfortable to be voiced. Accountability is an imperative part of growth. I can secretly write my feelings away, but if there’s no follow up- what’s the point? Ultimately, this is why I decided to publicly share this blog.\n I looked back at my old journals and had this instantaneous epiphany: my words stand as a pillar of my experiences. I’m learning that there’s growth in the midst of writing. There’s perceivable change behind every line. I wanted to start this blog a year ago. But damn, fear is a real thing. A solid year went by with 0 progress. A solid year of orienting my hand away from anything demanding vulnerability. A solid year of muting a process that fear had decided wasn’t worthy to be voiced. To be honest, I’m still afraid. Public blogs turn into palpable words which come with the consequence of a weight I’m not sure I’m ready to carry. However, it provides a backbone. Writing = introspection and being able to publicly share my thoughts = accountability.  If I don’t cease the moment and write… my journey will inevitably end up as an evanescent process.\nC.S Lewis wrote, “The typical expression of opening friendship would be something like, \‘What? You too? I thought I was the only one!\'” My heart is to capture my process, but more importantly, to empower others. Hopefully, this can turn into conversation starters and a push out of your own comfort zone! Vulnerability is hard but to love is to be vulnerable and that’s the kind of culture I hope to cultivate this year. So here’s to the start of authenticity and expressive passion that refuses to let fear shame its love for language.'
  }
]

module.exports.blogs = blogs;
